### PR TITLE
feat: add atom parent and child validation

### PR DESCRIPTION
**Pull request by nettohadi**
## Description

Some atoms can only under certain atoms. For example, Form.Item goes under Form. We are using the `requiredParents` field to validate if a child atom can go under a parent atom. Below are four cases that we're handling:

1. Only display the atoms if their required parents include the parent 

[LOOM DEMO](https://www.loom.com/share/c13139bd66a64fa1b143a77b6f5d2ed2)

2. Only display the atoms if the required parents of the parent doesn't include the atom 

[LOOM DEMO](https://www.loom.com/share/c7e5c8e42dcf4a69984ab2ce1f17a09f)

3. Only display the atoms without required parents 

[LOOM DEMO](https://www.loom.com/share/47b820a95cc34396aae0c8d4d929daaa)

4. Only display the required parents of the atoms in the parent element dropdown 

[LOOM DEMO](https://www.loom.com/share/ed345a1f236041c4b3d312a7d9a0175b)

## Related Issue(s)

Fixes [#1871 Atom parent and child validation](https://github.com/codelab-app/platform/issues/1871)

### CODE REVIEW

**Comment by webberwang** [comment]
Case #2 was the HtmlAtom added as required parent as well?

**Comment by nettohadi** [comment]
> Case #2 was the HtmlAtom added as required parent as well?

No, it wasn't.

**Comment by webberwang** [comment]
should it show up there?

**Comment by nettohadi** [comment]
> should it show up there?

Do we have HtmlAtom? If yes, I couldn't find it.

**Comment by nettohadi** [comment]
Did you mean `HtmlForm`, @webberwang? No, I didn't add the `HtmlForm` as the required parent of the `AntDesignFormItem`. That was why the `HtmlForm` showed up in the dropdown.

**Comment by webberwang** [comment]
> Did you mean `HtmlForm`, @webberwang? No, I didn't add the `HtmlForm` as the required parent of the `AntDesignFormItem`. That was why the `HtmlForm` showed up in the dropdown.

Oh right it's showing the AntDesignForm isn't a children, I suppose FormItem here doesn't have allowedChildren added which is why the rest is showing up. But that is not related to the point here

**Pull request merged**
